- LICENSES/Apache-2.0.txt
- README.md
- SECURITY.md
I had a sync with a colleague from OSPO team to identify the missing things in our repo. These are the missing things
> reuse compliance

- postgres/lib/PostgresService.js
> pg: Log hostname on success - for CF deployment

- db-service/test/cqn4sql/calculated-elements.test.js
> Calculated elements - some more tests

- db-service/lib/infer/index.js
- postgres/CHANGELOG.md
- postgres/lib/PostgresService.js
re https://github.com/cap-js/cds-dbs/issues/117
> fix: order by icu OR with (best-effort) mapping OR without collation

- db-service/CHANGELOG.md
- db-service/lib/SQLService.js
- test/scenarios/bookshop/index.js
- test/scenarios/bookshop/read.test.js
- test/scenarios/bookshop/update.test.js
@patricebender @BobdenOs Is there an appropiate test suite I could use for adding a test?
> update is only noop if not managed

- db-service/CHANGELOG.md
- postgres/CHANGELOG.md
- sqlite/CHANGELOG.md
> add changelog entries

- db-service/lib/cqn2sql.js
preparing to support default values in managed to-one associations with single foreign key
- tested manually
- additional test will be added after compiler starts to support this feature
> feat: managed association with default value for single FK

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/table-alias.test.js
- sqlite/lib/ReservedWords.json
- test/scenarios/bookshop/read.test.js
> sqlite/pg: Add smart quotation test

- db-service/lib/SQLService.js
- db-service/lib/deep-queries.js
- db-service/lib/fill-in-keys.js
- db-service/test/deep/deep.test.js
- package-lock.json
- test/bookshop/test/genres.cds
> Revert "Optimized deep delete"

- db-service/package.json
- package.json
- postgres/package.json
- sqlite/package.json
@danjoa @BobdenOs Do we have changes that force us to increase the peer dependency version as well?
> 1.2.0 in package.jsons

- postgres/package.json
- sqlite/package.json
the change for reducing the distinct usage impacts the postgres and sqlite service
> update version for db-service peer dependency

- db-service/test/cds-infer/negative.test.js
- db-service/test/cqn4sql/flattening.test.js
was already moved to a better place
> infer: remove duplicated test

- db-service/lib/cql-functions.js
There was a missing opening bracket
> fix brackets for matchesPattern

- db-service/lib/cqn2sql.js
- db-service/test/cqn2sql/__snapshots__/insert.test.js.snap
- db-service/test/cqn2sql/insert.test.js
Slightly optimised and better readable (hopefully :)
> Fine-tuning impl of INSERT_rows

- db-service/test/cqn4sql/functions.test.js
for the sake of completeness, add a test which shows how the dot operator can be used to connect multiple functions.
> cqn4sql: Add test for dot operator

- CONTRIBUTING.md
- db-service/lib/infer/index.js
- db-service/test/bookshop/db/booksWithExpr.cds
- db-service/test/cds-infer/calculated-elements.test.js
- db-service/test/cqn4sql/calculated-elements.test.js
the `args` of the `func` have not been considered, now the correct `join` is produced
> fix(calculated elements): path expressions in `func.args` within `xpr`

- db-service/lib/cqn4sql.js
> chore: add some comments

- package-lock.json
- sqlite/package.json
According to https://github.com/WiseLibs/better-sqlite3/releases/tag/v9.0.0 and https://www.sqlite.org/releaselog/3_43_2.html
> deps: upgrade to better-sqlite@9

- postgres/CHANGELOG.md
- sqlite/CHANGELOG.md
One time cosmetic change so that our release automatisation can detect the latest release pattern
> chore: streamline changelog format

- test/compliance/DELETE.test.js
- test/compliance/UPDATE.test.js
- test/scenarios/bookshop/delete.test.js
this PR build upon #325 and needs cap/cds/pull/3527 which will be available with the next `cds` release.
> test(`UPDATE`/`DELETE`): enable end2end tests with path expressions

- .github/workflows/release-please.yml
- hana/package.json
- release-please-config.json
> ci: include @cap-js/hana in release pipeline

- db-service/lib/infer/index.js
- db-service/test/cqn4sql/table-alias.test.js
reported in https://github.com/cap-js/cds-dbs/pull/428
> fix: consider `list` in `from.where`

- db-service/package.json
- hana/package.json
- package-lock.json
- postgres/package.json
- sqlite/package.json
@BobdenOs @patricebender force merge this?
> chore: bumps to "@sap/cds": ">=7.6" & "@cap-js/db-service": "^1.6.0"

- postgres/lib/PostgresService.js
- sqlite/lib/SQLiteService.js
... another offspring of Universal CSN
Can be merged right now as it serves all
> chore(cds.linked): revert Association extends struct

- db-service/test/cqn4sql/A2J/classes.cds
- db-service/test/cqn4sql/assocs2joins.test.js
follow up to review comment: https://github.com/cap-js/cds-dbs/pull/481#pullrequestreview-1908588280
> test: add more foreign key optimization tests

- hana/tools/docker/hxe/Dockerfile
This breaks HANA tests
This reverts commit c4b1d0edf25a8c1a5f078c6fce28d3298075eff6. (#500)
> chore: Revert "chore(deps): update saplabs/hanaexpress docker tag"

- hana/package.json
- postgres/package.json
- sqlite/package.json
@patricebender Do you think that works if we merge this PR just before the release?
> chore: increase db-service version for pg,hana,sqlite

- db-service/lib/cqn4sql.js
- db-service/test/bookshop/db/schema.cds
- db-service/test/cqn4sql/table-alias.test.js
- test/scenarios/bookshop/orderBy.test.js
this test should reproduce the issue.
I've verified that df19aa2 would fix it but I am not sure whether it's the correct fix.
> chore: fix collation issue for aggregations and subselects

- test/scenarios/bookshop/genres.test.js
> chore: more test adaptions for new odata adapter

- db-service/lib/deep-queries.js
Fix: what todo with multiple result responses. 
Now return beforeData.length or new InsertResult
> fix: multiple result responses

- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- db-service/test/cqn4sql/path-in-from.test.js
> revert: refactor(infer): consolidate two main functions

- hana/lib/HANAService.js
renames the feature flag to match the other databases `sql_simple_queries`
> chore: Align simple queries feature flag

- test/scenarios/bookshop/funcs.test.js
Activate tests https://github.com/cap-js/cds-dbs/pull/580
> test: Activate query functions tests

- db-service/lib/cqn2sql.js
- hana/lib/HANAService.js
Merge after cap/cds-mtxs/pull/969 is merged.
> wip: clean-up uiflex logic

- db-service/lib/cqn2sql.js
- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/assocs2joins.test.js
- db-service/test/cqn4sql/expand.test.js
- hana/lib/HANAService.js
- test/scenarios/bookshop/read.test.js
> fix: Support expand with group by clause

- hana/lib/drivers/hana-client.js
Also asked for review in mail thread
> chore(hana-client): add warning for missing thread pool configuration

- .release-please-manifest.json
- db-service/CHANGELOG.md
- db-service/package.json
- hana/CHANGELOG.md
- hana/package.json
This reverts commit e401aa6f5077e3b0de3d1cda2923cc096e4db27c.
@patricebender 
I'd try to revert the PR and let release-please redo its thing.
tags and releases I've deleted manually.
> chore: revert "chore: release main (#717)"

- README.md
- db-service/README.md
- hana/README.md
- postgres/README.md
- sqlite/README.md
- the cap-js dbs are now default -> remove `new`
- fix typos
- fix links
- improve wording and formatting
> docs: improve all `README.md`s

- db-service/lib/cqn2sql.js
We should change all occurences to
```js
const LOG = cds.log('db|sql')
if (LOG._debug) LOG.debug(...)
```
> fix(logging): from changes in @sap/cds

- hana/package.json
- package-lock.json
- test/cds.js
Requires next release of @sap/cds with internal PR 4589 merged
> deps: requires @sap/cds >= 8.2

- test/scenarios/bookshop/read.test.js
> test: add test for not in operator

- db-service/test/assocs/unmanaged-assocs.test.js
- hana/package.json
- package-lock.json
Updating the package-lock revealed that `db-service/test/assocs/unmanaged-assocs.test.js` uses an own mechanism for testing. I've worked around that now but is that test of value @patricebender?
> chore(deps): update package-lock.json

- db-service/lib/common/DatabaseService.js
- db-service/lib/common/generic-pool.js
- db-service/lib/infer/index.js
- sqlite/lib/SQLiteService.js
- test/scenarios/bookshop/funcs.test.js
As discussed in our call today... → required for renovated `cds.ql` + new `cds.xl`
> fix: funcs.test.js used wrong arguments for .where()

- hana/lib/HANAService.js
- test/scenarios/bookshop/read.test.js
fixes: https://github.com/cap-js/cds-dbs/issues/948
> fix: Fix expand aliasing

- db-service/lib/cql-functions.js
- hana/lib/HANAService.js
> feat: support for `SELECT.hint`

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/expand.test.js
- db-service/test/cqn4sql/path-in-from.test.js
> feat: support query modifiers at leaf of from ref

- .github/workflows/release-please.yml
- .release-please-manifest.json
- hana/package.json
- postgres/package.json
@BobdenOs @patricebender for some reason, only db-service and sqlite got released. need to find out why
> chore: revert release stuff

- test/scenarios/bookshop/read.test.js
- test/scenarios/sflight/lean-draft.test.js
fix test in order to merge https://github.tools.sap/cap/cds/pull/5033
> test: fix test with navigation

- db-service/lib/cqn2sql.js
- hana/lib/HANAService.js
- postgres/lib/PostgresService.js
- test/scenarios/bookshop/orderBy.test.js
> fix: consider `nulls first | last` on `orderBy`

- test/scenarios/bookshop/read.test.js
This reverts commit 5981433e1b1a7e208fee9953a3c9032c03455d13.
> chore: Revert "chore: remove unused odata calls (#1073)"

- hana/lib/HANAService.js
Error introduced in https://github.com/cap-js/cds-dbs/pull/1074
> fix(forUpdate): forUpdate optional

- db-service/lib/SQLService.js
- postgres/test/service-types.test.js
- postgres/test/streaming.compat.test.js
- sqlite/test/general/stream.compat.test.js
This reverts commit 86203ab682e9bb58252d5dc0e1b74cc036c9da75.
> chore: Revert "refactor: remove stream_compat (#1139)"

- db-service/package.json
- hana/package.json
- package.json
- postgres/package.json
- sqlite/package.json
Replaces the placeholder value "SEE LICENSE" with "Apache-2.0" as the project is licensed under Apache 2.0, and the LICENSE file contains the full license text.
> chore: adapt license entry

- package-lock.json
hopefully fixes https://github.com/cap-js/cds-dbs/security/dependabot/28
> chore: update tar-fs manually

- db-service/lib/SQLService.js
- db-service/lib/cqn2sql.js
- test/compliance/DELETE.test.js
- test/compliance/INSERT.test.js
- test/compliance/SELECT.test.js
- test/compliance/UPDATE.test.js
- test/compliance/UPSERT.test.js
- test/compliance/resources/db/complex/associations.cds
- test/compliance/resources/db/complex/associationsUnmanaged.cds
- test/compliance/strictMode.test.js
This reverts commit 47d6ed765800c5bd3fa6ff7b920efb5ac4481c63.
> chore: Revert "feat: deep delete for hierachies (#1217)"

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/compare-structs.test.js
- db-service/test/cqn4sql/flattening.test.js
- db-service/test/cqn4sql/structure-access.test.js
also improve corresponding error message
> fix: arithmetic operators can only be used with scalar operands

- db-service/lib/SQLService.js
- db-service/lib/cqn2sql.js
- hana/lib/HANAService.js
> fix: revert own resolve
