- postgres/lib/PostgresService.js
Adding support for acquireTimeoutMillis pool setting to resolve the ResourceRequest timed out problem. 
More information about the problem and a solution is available at the following URL, but they are not part of PostgresService. 
https://cap.cloud.sap/docs/advanced/troubleshooting#why-are-requests-occasionally-rejected-with-acquiring-client-from-pool-timed-out-or-resourcerequest-timed-out
> Adding acquireTimeoutMillis Pool Parameter

- db-service/CHANGELOG.md
- db-service/lib/SQLService.js
`SQL` does not care about the casing of the key words. Therefor it is allowed to do `SELECT`, `select` and `SeLeCt` which will now be properly identified as a reading query.
> [FIX] Make result check for plain SQL queries case insensitive

- .github/workflows/test.yml
- db-service/package.json
- package-lock.json
- postgres/test/__snapshots__/csn2postgres.test.js.snap
`"@sap/cds": ">=7"` -> leads to `cds@7.0.0` which still depends on `compiler@3.9.2`
> actions: Use compiler v4^ in `package-lock.json`

- postgres/package.json
Currently, we do this in a hacky way in `cds deploy` - we should instead do it more centrally in the plugin.
Should fix https://github.com/cap-js/cds-dbs/issues/100
> Postgres: schema_evolution = 'auto' by default

- .github/CODEOWNERS
- postgres/CHANGELOG.md
- postgres/lib/PostgresService.js
- postgres/test/connect.test.js
- postgres/test/service-az.json
- postgres/test/service-btp.json
enhancing the `credentials` obj by a boolean value to be able to properly connect to a pg db running on azure.
also added tests for major connectivity scenarios (docker, btp, azure).
> feat: enable azure pg connectivity

- db-service/lib/infer/join-tree.js
- db-service/test/cqn4sql/inline.test.js
an association which is part of a `ref` which ends up in an `inline` expression, is always join relevant -> need to correctly set the marker
> infer: correctly merge `inline` columns into join tree

- db-service/package.json
- postgres/package.json
- sqlite/package.json
The links at https://www.npmjs.com/package/@cap-js/postgres are currently very generic. I think we should point them to the now public GitHub repository.
> Point links at npmjs to GitHub repository

- db-service/lib/cqn2sql.js
- db-service/lib/cqn4sql.js
- db-service/test/cqn2sql/__snapshots__/delete.test.js.snap
- db-service/test/cqn2sql/__snapshots__/select.test.js.snap
- db-service/test/cqn2sql/expression.test.js
- jest.config.js
- package.json
- postgres/lib/PostgresService.js
- postgres/package.json
- sqlite/lib/SQLiteService.js
When using the `=` and `!=` cqn operator it should consider `NULL` as equal to `NULL`. Which means that for `SQL` it is required to use other operators then `=` and `!=`. For SQLite it is `IS` and `IS NOT`. For Postgres it is `is not distinct from` and `is distinct from`. Which in certain cases does not apply optimizations that `=` and `!=` have on the database.
With this change it is checked that both sides of the operation cannot contain `NULL` as result. Which allows for the usage of `=` and `!=`. This will mostly only be true when doing simple expressions like `... WHERE ID = 201`. For anything more complex like `... WHERE ID = (200 + 1)` it won't be capable of guaranteeing that both side will never be `NULL`.
> Why do both sides have to not be `NULL`
When an `=` or `!=` operator …
> feat: Reduce distinct from usage - part 1

- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- db-service/test/cqn4sql/column.element.test.js
for a flat model, we must attach the foreign key which is adjacent to it's association as the columns `element` property. If such a flat fk is found next to the association in the containing entity, it is used as the `element` rather than the key in the target of the association.
fixes #165
> cqn4sql: attach adjacent fk adjacent to assoc as element of column

- db-service/lib/cqn2sql.js
- db-service/test/cqn2sql/__snapshots__/select.test.js.snap
- db-service/test/cqn2sql/expression.test.js
- postgres/lib/PostgresService.js
- sqlite/lib/SQLiteService.js
@BobdenOs : this is reverting the symmetric support for IS and IS NOT. 
When I saw that very many ON conditions got translated to the like of `WHERE author_ID IS Authors.ID`, I recalled why I didn't have this symmetry in the initial implementation. → the comment in changed files.
Fixes #156 
Replaces #157
> [IMPORTANT:] Using is distinct from only

- .github/workflows/test.yml
- db-service/package.json
- hana/jest.config.js
- hana/package.json
- hana/tools/docker/hxe/ci.yml
- hana/tools/docker/hxe/ready.sh
- hana/tools/docker/hxe/start.sh
- jest.config.js
- package.json
- postgres/jest.config.js
- postgres/package.json
- sqlite/package.json
- sqlite/test/bookshop.test.js
- sqlite/test/compliance.test.js
- sqlite/test/sflight.test.js
- test/cds.js
Change the approach of doing multi workspace testing
```sh
npm t -ws # runs all test in the workspaces in order of the package.json workspaces array
npm t -w postgres -w hana # will run the test command for postgres and hana
```
Which allows each package to do their `start` script before running their tests. Also it allows for all the packages to have their own local `jest.config.js` files. Which allows `sqlite` to have a smaller `testTimeout` then `postgres` and `hana`.
> test: Split test script into each package again

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/expand.test.js
- db-service/test/cqn4sql/model/collaborations.cds
This resolves a dump found by a customer:
```log
TypeError: Cannot read properties of undefined (reading 'ref')
at calculateOnCondition (lib/cqn4sql.js:1630:17)
at onCondFor (lib/cqn4sql.js:1607:13)
at getWhereExistsSubquery (lib/cqn4sql.js:1852:27)
at _transformFrom (lib/cqn4sql.js:1479:38)
at getTransformedFrom (lib/cqn4sql.js:1436:14)
at cqn4sql (lib/cqn4sql.js:72:53)
at transformSubquery (lib/cqn4sql.js:891:12)
at expandColumn (lib/cqn4sql.js:776:22)
at handleExpand (lib/cqn4sql.js:396:40)
at /Users/patricebender/SAPDevelop/dev/cds-dbs/db-service/lib/cqn4sql.js:322:32
at getTransformedColumns (lib/cqn4sql.js:350:21)
at transformSelectQuery (lib/cqn4sql.js:121:41)
at cqn4sql (lib/cqn4sql.js:76:28)
```
> cqn4sql: fix transformation of nested expand

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/model/cap_issue.cds
- db-service/test/cqn4sql/where-exists.test.js
Inspired by #169
---
the issue here was that we had a where condition like
`where exists foo[id=1] or exists foo[id=2]` with foo being an association `foo : Association to one Foo on foo.ID = foo_ID;`.
While building up the where exists subqueries, we calculate unique table aliases for `foo`, which results in a table alias `foo2` for the second condition of the initial where clause. Now, if we incorporate the on-condition into the where clause of the second where exists subquery, we must replace the table alias `foo` from the on-condition with `foo2`.
> cqn4sql: make sure to always use calculated alias in custom on conditions

- db-service/lib/cqn2sql.js
When updating a `many` column type. The `json` value is converted into a `SQL` string, but is send as a parameter.
> fix: pass json as parameter instead of sql string

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/table-alias.test.js
easy fix, just check if `ref[0]` is an entity, if so, it must not be part of the flat name.
---
@stewsk please have a look
> cqn4sql: for `$self` replacements, do not use table alias for flat name

- .github/CODEOWNERS
With this change, I want to achieve that people feel more obligated to review a particular change.
This can be achieved by restricting the code ownership to specific areas. E.g. @vobu @gregorwolf @sebastianesch might be interested in `postgres` while not being interested in changes in e.g. `cqn4sql`.
Our product owners @stewsk @johannes-vogel and @danjoa are still owning everything and hence are able to approve changes in all areas.
If you have suggestions how to improve my initiative, please let me know.
---
@David-Kunz  @sjvans
would you like to be a code owner in a particular area?
> Update CODEOWNERS > narrow down scopes

- test/bookshop/db/schema.cds
- test/scenarios/bookshop/update.test.js
there was an issue with `postgres v1.1.0` - reported in https://github.com/cap-js/cds-dbs/issues/201 - which has been resolved in the meantime. Adding a test for bookkeeping.
> test: add scenario for upsert `array of`

- db-service/lib/fill-in-keys.js
- db-service/test/deep/deep.cds
- db-service/test/deep/deep.test.js
I've added a test to reproduce the problem. Still needs to be fixed.
> fix: deep insert with backlinks as key in children

- sqlite/lib/SQLiteService.js
- sqlite/test/general/datetime.test.js
- sqlite/test/general/testModel.cds
Oliver has switched the odata-v2 proxy to use the new db layer in his tests.
This reveals a problem with datetime elements as key.
On first glance, the ISO function formats datetime values as timestamps which cannot be found anymore as we don't apply the same function on where clauses. Alternatively, we must not use the function for datetime elements.
caused by #131
> reproduce issue with timestamp as key

- db-service/lib/cqn4sql.js
- db-service/test/bookshop/db/schema.cds
- db-service/test/cqn4sql/DELETE.test.js
- db-service/test/cqn4sql/tupleExpansion.test.js
When having a scoped query, as in the test example, we must pass the context for an infix filter (that is the entity where the filter is resolvable in) if the filter is not part of the last `ref` and hence not part of the `elements` of the query.
---
@patricebender FYI.
When testing #212 with the current runtime implementation, we observed that a request like this causes a crash in cqn4sql.
If you have some time, you could have a look. Assumption is that the association in the filter is flattened to its foreign key.
> cqn4sql: pass context for association expansion

- db-service/lib/cqn2sql.js
- package-lock.json
- test/compliance/SELECT.test.js
`better-sqlite3@8.6.0` includes an upgrade of `sqlite3` which contains a performance optimization for `json` functions ([changelog](https://www.sqlite.org/releaselog/3_43_0.html#:~:text=Performance%20enhancements%20to%20JSON%20processing%20results%20in%20a%202x%20performance%20improvement%20for%20some%20kinds%20of%20processing%20on%20large%20JSON%20strings.))
The performance optimization seems to take the trade of that it uses more memory. Which made the `lean-draft` tests run into `SQLITE_NOMEM` (out of memory) errors. After some investigating this seems to be related to the solution used to support 50+ columns in select statements. This PR switches to use `json_patch` which is equal to `Object.assign({...},{...})`. Which seems to make the behavior as expected again. Might even be a …
> fix: better-sqlite3@8.6.0

- .github/CODEOWNERS
- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- db-service/test/cqn4sql/calculated-elements.test.js
- db-service/test/cqn4sql/pseudo-variable-replacement.test.js
- db-service/test/cqn4sql/where-exists.test.js
this is an easy fix, we must link the calculated element first in `infer` then, we can insert the calculated element as wildcard replacements as we do with all other columns. In the end, we must only deduplicate the already-inserted wildcard replacment.
---
also applied some minor changes to the `CODEOWNERS` file. Now our POs should be requested for review for every file.
> calculated elements: enable smart wildcard replacements

- db-service/lib/cql-functions.js
- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- db-service/lib/infer/join-tree.js
- db-service/test/bookshop/db/booksWithExpr.cds
- db-service/test/cds-infer/calculated-elements.test.js
- db-service/test/cqn4sql/calculated-elements.test.js
- sqlite/lib/SQLiteService.js
This change contains several fixes for the calculated elements on read:
- If multiple calculated elements share the same join node, make sure that refs are properly rewritten to the correct TA
- make sure that infix filter arguments in calculated elements are properly massaged into join arguments
- make sure that such an infix filter can also be a calculated element by itself
- provide a base context for function arguments making sure that aliases are properly added to the refs
other changes:
- add test - which is currently skipped - that shows that calculated elements are currently not properly rejected after `where exists` arguments
> calculated elements: fixes and enhancements

- postgres/pg-stack.yml
[pg 16 is now latest ](https://github.com/docker-library/postgres/commit/7df6bc166fbf0d7f28c85700235012317a22f88e)and seems to break with our test setup.
revert to 15 for running pipelines.
BLI created to analyze issue with pg 16.
> chore: use pg 15 image

- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- db-service/test/cds-infer/negative.test.js
- db-service/test/cqn4sql/where-exists.test.js
- postgres/lib/func.js
before this change, there was a dump for this.
> cqn4sql: reject non associations following `exists` predicate

- .github/workflows/release-please.yml
- .release-please-manifest.json
- CONTRIBUTING.md
- release-please-config.json
follow steps in https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md which is targeting monorepo setups.
To use release please we need to install the `release-please` npm package: `npm i release-please -g`.
work for #109
---
inspired by https://github.com/Financial-Times/origami → those guys are releasing dozens of components from their monorepo with `release-please`
> ci: bootstrap release please configuration

- .github/workflows/release-please.yml
if the `GITHUB_TOKEN` is used, PRs created by the github actions bot do not trigger workflow runs
> ci: use cap bots to create release please PR

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/DELETE.test.js
- db-service/test/cqn4sql/UPDATE.test.js
this change enables the usage of path expressions in `where` clauses of `DELETE` queries.
If there is a path expressions found in a `where` of an `DELETE`, the `where` clause is cut out of the `DELETE` and is put into a `where` clause  in a dummy subselect, which is then transformed by `cqn4sql`. The result of the transformation is then put into the `DELETE` again, as `exists <subquery>`.
--> `DELETE.where = ['exists', cqn4sql(subquery)]`
---
based on #325
fix https://github.com/cap-js/cds-dbs/issues/159
> feat(`DELETE`): enable path expressions 

- hana/lib/HANAService.js
Without this change every query is wrapped inside a `DO BEGIN` which allows for multiple queries to be executed, but this comes with a bit of an overhead. So now flat queries (without expands) are now done as a `SELECT` directly.
Additionally the `_json_` column is returned as an `NVARCHAR` as the HANA network protocol for `NCLOB` requires additional `FETCH` calls which cause a dramatic overal request response time.
> feat: use a simple select for flat queries

- db-service/test/cds-infer/elements.test.js
- db-service/test/cqn4sql/flattening.test.js
if a virtual column is the only column in a given clause, we strip the clause from the query as the virtual column doesnt materialize.
> chore: enable skipped tests

- db-service/lib/infer/index.js
- db-service/test/cqn4sql/where-exists.test.js
for assocs embeeded in structures, this check was not executed. This situation can only happen with structured csn. However, better to have it fixed. :)
> fix: non-fk access in filter conditions are properly rejected

- sqlite/lib/SQLiteService.js
- test/scenarios/bookshop/funcs.test.js
null values cause type error as e. g. _.getUTCFullYear()_ cannot be called on _null_.
If you have an alternative implementation, I'm open.
> fix: date functions with null value

- postgres/CHANGELOG.md
- postgres/lib/build.js
- identical output folder structure for node.js and java as documented in Capire
- use existing package.json from db folder instead of generated one
> fix: `cds build` now generates the correct output folder structure for Node.js and Java apps.

- .github/workflows/hana.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
See
- https://github.com/actions/checkout/releases/tag/v4.0.0
- https://github.com/actions/setup-node/releases/tag/v4.0.0
Major version change due to internal upgrade from Node 16 to 20.
> ci: Update actions/checkout and actions/setup-node to v4

- .github/workflows/conventional-commits.yml
Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload. 
see [github docs](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)
---
[this commit](https://github.com/amannn/action-semantic-pull-request/commit/e9fabac35e210fea40ca5b14c0da95a099eff26f) is now used instead of the tag
> ci: prefer SHA over tag for github action

- hana/lib/HANAService.js
After the findings that the old `HANA` Service was sometimes running expand queries in parallel. It was determined that this should still be done. Therefor this PR tries to achieve the same results as the old implementation. While still only sending a single statement to `HANA`.
> perf: HANA parallel expand

- sqlite/test/deep/deepInputProcessing.test.js
in #32 a test has been added, I assume it should not be the `.only` one run as part of this test suite. @johannes-vogel
> test: remove accidental (?) .only

- db-service/lib/cqn2sql.js
- hana/lib/HANAService.js
This fix is important to support calculated elements. Without it we generate inserts that try to fill in data to them, even if there's no data in the input data payload. 
Would be good if we could public a hotfix asap. I wanted to use it in a demo on Monday.
> fix(cqn2sql): supporting calculated elements

- db-service/lib/SQLService.js
For draft tables, no db constraints for cascading delete is added.
Also no db constraints are added for compositions of one.
We should first clarify under which circumstances we can rely on it.
> fix: do not rely on db constraints for deep delete

- hana/lib/HANAService.js
In the base `cqn2sql` implementation the `orderBy` is checked for its length. This check was missing in the HANA Service.
> fix: ignore empty order by

- postgres/lib/PostgresService.js
According to the Postgres Documentation `jsonb` is faster then the `json` type. 
Additionally there is no `equal` operator defined for the `json` type while there should be one defined for `jsonb`. Which became apparent when using `distinct` while also having an expand. As the expand column will be of `json` type it will also be compared for `distinct`.
> fix: switch Postgres from json to jsonb

- db-service/lib/common/session-context.js
- hana/lib/drivers/hana-client.js
- hana/lib/drivers/hdb.js
Made it so that the getters are defined as enumerable. Allowing the hana driver to use simple `in` loops.
> fix: enumeration issue with session context in @cap-js/hana

- hana/lib/HANAService.js
The current implementation relied upon the unique aliases provided by `cqn4sql`. This works in most scenarios, but stops working for the `HANAService` specifically as the aliases are only locally unique. While the `WITH` clauses requires globally unique aliases. Therefor this change uses the parent alias to ensure globally unique aliases.
```cql
SELECT Books {
author {
texts { * } -- Alias will be texts
books {
texts { * } -- Alias will be texts2
}
},
genre {
texts { * } -- Alias will be texts
}
}
```
with this change the aliases for the `HANAService` are transformed into
```cql
SELECT Books {
author {
texts { * } -- Alias will be Books.author.texts
books {
texts { * } -- Alias will be Books.author.books.texts2
}
},
genre {
texts { * } -- Alias will be Books.genre.texts
}
}
```
> fix: Ensure globally unique aliases with large expand queries

- db-service/lib/cqn2sql.js
Excluding associations from UPSERT broke a test in @sap/cds, so this PR restores the former behavior for the time being which let updates to associations slip through and fail with a database error. 
We need to follow up on what the correct behavior should be...
> fix: Restore former deep upsert behavior / error

- db-service/lib/cqn4sql.js
- db-service/test/bookshop/db/schema.cds
- db-service/test/cqn4sql/tupleExpansion.test.js
this was forgotten and becomes especially important with universal csn in the context of lean draft. Where a `SiblingEntity` association might have a structured key comparison in the on condition.
> fix(cqn4sql): expand structured keys in on-conditions

- db-service/lib/cqn2sql.js
- package-lock.json
- sqlite/lib/SQLiteService.js
- sqlite/package.json
With the release of `better-sqlite3@9.3.0` it bumped the sqlite version to `3.45.0`. Which comes with a complete rework of the `json` functions. With the big difference being that it now supports an internal `jsonb` format. Which is supposed to be only used by `sqlite` itself, but with this new change all the `json` functions accept `binary` data as the `jsonb` format. Therefor as the json that we produced was being converted into `Buffer`s it resulted in `better-sqlite3` providing them as `binaries` to the `json_each` function which made it interoperate it as an malformed `jsonb`. So this change forced the `json` to be bound as a `strings` which makes everything in its own behavior.
Additionally now that the `json_insert` function has a `jsonb_insert` equavelant it fixes a memory issue …
> fix: make @cap-js/sqlite work with better-sqlite3@9.3.0

- db-service/lib/cqn2sql.js
- test/scenarios/bookshop/localization.test.js
The implementation was simply plain wrong, e.g. for query`SELECT localized.title from Books` the `$user.locale` in the infix filter of the `localized` association was translated to `session_context('$user.id')` instead of `session_context('$user.locale')` 
→ see the added tests
> fix(cqn2sql): $user.locale refs

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/tupleExpansion.test.js
the error message calculation was over-enginereed. With little value. It is sufficient to tell the user that the structures are not comparable, no need to mention every step which was not found in the msg. also: exit early once one step was not found in the other side of the comparison
**Note:** Best to review this change with whitespaces hidden.
> chore: improve error message for struct comparison

- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- db-service/lib/infer/join-tree.js
- db-service/test/cqn2sql/__snapshots__/expression.test.js.snap
- db-service/test/cqn2sql/__snapshots__/select.test.js.snap
- db-service/test/cqn4sql/assocs2joins.test.js
- db-service/test/cqn4sql/table-alias.test.js
if we have a query hierarchy, make sure that subqueries always have aliases which are unique to the outer scope. This does not yield more functionality for a user, since if we would want to address elements of an outer query  (i.e. make use of correlated subqueries), one has to define an alias beforehand.
> fix: always generate unique subquery aliases

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/DELETE.test.js
because of odata special magic, a tokenstream with `length === 1` which only has a value, is transformed into a full key tuple comparison, e.g. to make this possible: `select from bookshop.Books[42]`. If we now have a list, with exactly one entry, the same logic kicked in and transformed the single value in the token stream to such a key comparison.
to fix this, we now skip processing of lists which only consist of values, which circumvents the described issue.
> fix(`cqn4sql`): only transform list if necessary

- db-service/test/cqn2sql/__snapshots__/select.test.js.snap
- db-service/test/cqn2sql/select.test.js
Xpr with combinations of vals/refs should not have any additional brackets.
> chore: test for xpr support in functions

- db-service/lib/cqn4sql.js
In contrast to 4odata, on conditions are not rewritten in universal csn. 
In particular `on foo.id = $self.foo_id` is not rewritten to `on foo.id = foo_id` as in 4odata. 
@patricebender : **please double-check** whether this fix is correct. 
Find info about fixed tests in jest.config-usn.js.
> fix(ucsn): Support $self.<element> in on conditions

- db-service/lib/cql-functions.js
This patch improves the error handling for #127 by showing a slightly better understandable error message to the user.
Before:
After:
Seems like CAP expects an Error instance these days, because it accesses error.message.
`Parameter 'error.message' must be type of 'string'`
@sap/cds: 7.3.1
@sap/cds-compiler: 4.3.2
@sap/cds-dk (global): 7.3.2
@sap/cds-fiori: 1.1.0
@sap/cds-foss: 4.0.2
@sap/cds-mtxs: 1.12.1
@sap/eslint-plugin-cds: 2.6.3
Node.js: v18.19.1
cds-dbs: 1.3.1
> fix: Throw 'new Error' instead of string on $search with multiple words

- db-service/lib/cqn4sql.js
- db-service/test/bookshop/db/schema.cds
- db-service/test/cqn4sql/where-exists.test.js
if a `ref` of length > 1, has `ref[0] === 'self'`, the `$self` can just be ignored. `$self` comparisons have only special semantics if compared to an association. With this change, we become more robust in that regard and do not prepend wrong table aliases for the case `$self.<assoc>.<element>` - in that case, we must ensure that the alias of the association is used and not the alias of the entity. Follow up #468
> fix(`cqn4sql`): be robust against `$self.<element>` references

- db-service/lib/SQLService.js
- hana/lib/HANAService.js
Currently the `@sap/cds` infer does not support `SELECT.join` queries. The `Query.target` for `join` queries always returns `undefined`. So when trying to identify `unresolved` queries the output converters where no longer being applied to `join` queries.
There have been discussions about adding `join` support to the `@sap/cds` infer function. If this will be available soon it might already solve this issue. If this still takes longer it might be required to add this quick fix.
> fix: Allow SELECT.join queries again with full infer call

- hana/lib/HANAService.js
With `@cap-js/hana` I get the following error (in `dev/cds-mtxs/test/bookshop`):
```
cds run --profile hana --resolve-bindings
```
```
TypeError: Cannot read properties of undefined (reading 'driver')
at get factory [as factory] (/Users/D061687/Desktop/dev/cds-dbs/hana/lib/HANAService.js:32:76)
at <instance_members_initializer> (/Users/D061687/Desktop/dev/cds-dbs/db-service/lib/common/DatabaseService.js:18:54)
at new DatabaseService (/Users/D061687/Desktop/dev/cds-dbs/db-service/lib/common/DatabaseService.js:8:1)
at new SQLService (/Users/D061687/Desktop/dev/cds-dbs/db-service/lib/SQLService.js:321:5)
at new HANAService (/Users/D061687/Desktop/dev/cds-dbs/hana/lib/HANAService.js:16:1)
at _use (/Users/D061687/Desktop/dev/cds/lib/srv/factory.js:23:42)
at _use …
```
> fix: `TypeError` for `cds bind` in MTX scenario

- db-service/lib/cqn2sql.js
- test/scenarios/bookshop/insert.test.js
`INSERT({ stock: undefined, ID: 223, title: 'Harry Potter' }).into(Books)` had led to `SqliteError: malformed JSON`
> fix: `INSERT` with first `undefined` value

- db-service/lib/cqn4sql.js
- db-service/lib/infer/join-tree.js
- db-service/test/cqn4sql/A2J/classes.cds
- db-service/test/cqn4sql/assocs2joins.test.js
if the path resolves to a foreign key, we should not create a join for the last association, instead we shortcut to the foreign key. This was not considered for join relevant paths. 
fix #479
> fix: optimize foreign key access in a join relevant path

- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- db-service/lib/infer/join-tree.js
- db-service/test/cds-infer/elements.test.js
- db-service/test/cds-infer/source.test.js
- db-service/test/cqn4sql/model/withParameters.cds
- db-service/test/cqn4sql/with-parameters.test.js
consider `args` in a `ref` for path expression. If no arguments are provided, but we navigate along a parameterized entity, we provide an empty argument list (same for `@cds.persistence.udf`)
→This is in line with the compiler behavior
> feat: support path expressions for parameterized entities

- renovate.json
for now, we don't update as this seems to break
hana tests: https://github.com/cap-js/cds-dbs/actions/runs/8158113823/job/22299286592
> chore(renovate): ignore `saplabs/hanaexpress`

- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- test/scenarios/bookshop/read.test.js
there are cases where `join.args` have a `_target` property -> better to just do the lookup by myself
> refactor: do not rely on `_target`

- renovate.json
Dashboard can be found here: https://github.com/cap-js/cds-dbs/issues/502
---
I think, we don't need it.
> chore(renovate): disable dependency dashboard

- db-service/lib/cqn2sql.js
- test/compliance/keywords.test.js
without that fix all elements not specified in entries would be nulled.
bug introduced with 78fe10b
> chore: fix 78fe10b

- db-service/lib/cqn4sql.js
- db-service/lib/search.js
- db-service/test/cqn4sql/search.test.js
- test/scenarios/bookshop/index.js
- test/scenarios/bookshop/search.test.js
Although this use case is probably not really common or makes much sense, there were some failing `cds` tests which should be fixed by this.
---
If the query contains a `group by`, the search is performed on the queries
columns. If one of those columns is an aggregate function,
we must put the search term in the `HAVING` clause instead of `WHERE`.
Since the logical processing order of SQL queries is `FROM -> WHERE -> GROUP BY -> HAVING -> SELECT -> ORDER BY` the aggregated results are not accessible in the `WHERE` clause.
This led to an error:
```sql
> Uncaught SqliteError: misuse of aggregate: COUNT() in:
SELECT
COUNT(Books.stock) AS foo
FROM
sap_capire_bookshop_Books AS Books
WHERE
(IFNULL(INSTR(LOWER(COUNT(stock)), LOWER(?)), 0))
GROUP BY Books.title
```
With this change, the …
> fix(search): search on aggregated results in HAVING clause 

- hana/lib/HANAService.js
- sqlite/lib/SQLiteService.js
same will be done for postgres once available.
follow-up #525 #526
> chore: use `cds.compiler.to.<…>.keywords` instead of requiring compiler

- db-service/lib/SQLService.js
- hana/lib/HANAService.js
- test/compliance/SELECT.test.js
- test/scenarios/bookshop/read.test.js
When using `forUpdate` or `forShareLock` now `sqlite` and `postgres` will both use normal `root` queries. While for HANA it will first execute the lock SQL and then execute the query with the lock removed. As HANA does not allow locks when using sub queries. 
Example:
```SQL
SELECT ID FROM (SELECT * FROM Books) FOR UDPATE ID NO WAIT -- cannot identify Books as the lock target table
```
When using expands in lock queries only the lock on the root table is guaranteed.
> chore: return normal results for lock queries

- hana/lib/HANAService.js
- test/scenarios/bookshop/insert.test.js
The fix was not required for the pipeline as the hana version is <= 2.
Local testing with hana cloud reveals that runBatch can be used and does the job for both drivers.
> fix: mass insert for unknown entities

- db-service/lib/SQLService.js
When the query does not have clauses that can rely on the output columns all columns are replaced. When there are clauses that might rely on the the output columns all expands are removed from the columns.
> fix: Reduced count query complexity when possible

- db-service/lib/infer/index.js
- db-service/test/bookshop/db/schema.cds
- db-service/test/cds-infer/negative.test.js
an `expand` or `inline` on a `many` type has no defined behavior, yet.
→ as of now this is an error because the path cant be resolved (expand / inline without `.elements`)
we should reject it with a proper error, just as the compiler does for static views.
> fix(`inline`, `expand`): Only accept on structures, assocs or table aliases

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/table-alias.test.js
this is a fix for #546, where those properties in some cases got lost.
> chore: keep sorting props `asc`, `desc`, `nulls`

- db-service/lib/deep-queries.js
- db-service/lib/fill-in-keys.js
- test/compliance/UPDATE.test.js
Flat update with or on keys in where resulted in error `UNIQUE_CONSTRAINT_VIOLATION`.
Solution: Only enrich data with keys from where for deep update.
> fix: flat update with arbitrary where clauses

- db-service/lib/cqn2sql.js
- test/bookshop/db/data/sap.capire.bookshop-Authors.csv
- test/bookshop/db/schema.cds
- test/scenarios/bookshop/update.test.js
it doesnt make sense to `UPDATE`, `DELETE` or to `INSERT` a virtual element, which only exists during runtime, such as:
- `virtual` elements
- calculated elements
- associations
> fix: only consider persisted columns for simple operations

- db-service/lib/infer/index.js
- db-service/test/cds-infer/negative.test.js
- db-service/test/cqn4sql/flattening.test.js
- db-service/test/cqn4sql/table-alias.test.js
`refs` in `order by` can address queries own columns, if such a `ref` traverses an association to a non-foreign key field as in this example: 
```sql
SELECT from bookshop.Books as foo {
ID,
author,
coAuthor as co
}
order by
co.name -- join with query "foo" not possible
```
we must reject the traversal, as the join partner of `Authors` is the query itself
fix(`order by`): do not mistake simple name with infix filter
another fix do not mistake simple name with infix filter: If
the query has `columns` but they solely consist of `*`, 
`cqn4sql` wrongly assumed that an association traversal has to be resolved in the queries elements, this lead to a 
confusing error complaining that only foreign key of assocs can be traversed in infix filters.
> fix(`order by`): reject non-fk traversals of own columns in order by

- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- db-service/lib/infer/join-tree.js
- db-service/test/bookshop/db/booksWithExpr.cds
- db-service/test/cqn4sql/calculated-elements.test.js
- db-service/test/cqn4sql/table-alias.test.js
This is necessary if we expose an association in the inner query and traverse it in the outer query:
```cds
select from (select from Books) { author.name }
```
to come up with a proper join node, we must add a table alias around the subquery in from.
I came up with `__select__` as artifical name. To make it always unique, I request a unique alias from the subquery based on `__select__`, the subquery knows all outer aliases and is able to calculate a universally unique alias.
bugs found in #590
> fix: assign artificial alias if selecting from anonymous subquery

- db-service/lib/cqn2sql.js
- hana/lib/HANAService.js
- postgres/lib/PostgresService.js
Add `toLowerCase()` to Postgres quoting. Align regex with `@sap/cds-compiler`.
> fix: Align all quote functions with @sap/cds-compiler

- hana/lib/HANAService.js
When having an order by clause which references a column which is renamed for the actual result. This change makes sure that the alias is considered. Additionally if ordered column is not being selected it will expose it with an internal alias.
While fixing most cases there is a strange gap. Which fails with the cryptic error message: `additionalMatFields.empty()`
> fix(hana): Reference column alias in order by

- hana/lib/HANAService.js
- hana/lib/cql-functions.js
- hana/test/fuzzy.cds
- hana/test/fuzzy.test.js
With the old database service it was possible to define a custom fuzzy search cqn.
The test implements it like:
```js
{
func: 'CONTAINS',
args: [
{ list: [{ ref: ['ID'] }, { ref: ['NAME'] }] },
{ val: hanaSearchTerm },
{ func: 'FUZZY', args: [{ val: 0.8 }, { val: 'similarCalculationMode=searchCompare' }] }
]
}
```
But according the HANA documentation this is incorrect. As `CONTIANS` is not a function it is actually a `predicate`. Which would be defined like:
```js
{
xpr: [
'CONTAINS',
{
xpr: [
{ list: [{ ref: ['ID'] }, { ref: ['NAME'] }] },
{ val: hanaSearchTerm },
'FUZZY',
{xpr: [[{ val: 0.8 }, { val: 'similarCalculationMode=searchCompare' }]]}
]
}
]
}
```
Additionally the `contains` function from the OData spec clashes with the HANA internal function name. Which means that the custom …
> fix(hana): Allow custom fuzzy search cqn

- hana/lib/drivers/hana-client.js
- sqlite/test/general/stream.test.js
When reading a stream from hana-client and writing it directly back into the database results in the wrong encoding / decoding of the stream. To solve this all encoding / decoding is removed from the stream as it is not required except for base64 encoding when converting it into a raw json stream. Which has been moved to the only location this is used.
> fix(hana): Remove encoding from hana-client streams

- hana/lib/cql-functions.js
- test/scenarios/bookshop/funcs.test.js
According to the `concat` definition it is allowed to provide more then two arguments to the function. The native HANA `concat` function only allows two arguments. Therefor this overwrite is taken from the base implementation to allow for more arguments.
> fix: Add multi `concat` function to `@cap-js/hana`

- db-service/package.json
- package-lock.json
this is needed for https://github.com/cap-js/cds-dbs/pull/590
deps: require `>= sap/cds-compiler@4.9`
> deps: require `>= sap/cds@7.9.0`

- db-service/lib/cqn2sql.js
- db-service/test/cqn2sql/expression.test.js
- hana/lib/HANAService.js
- test/scenarios/bookshop/read.test.js
In the case of Postgres all queries doing `x = null` where being translated to `x is $1` which causes trouble as the operator name is `is null` unlike the SQLite operator which is just `is`.
The Postgres error was already resolved in the HANA Service, but the SQL Execution plan cache optimization caused trouble when comparing with `LOB` type columns. As HANA does not support compare operation on `LOB` columns. There for the only allowed operators on the `LOB` columns is `is (not) null`. Which also causes the issue that SQLite and Postgres are both allowed to execute `null = (LOB)`, but for HANA this causes a SQL error. As `null = ...` always returns null it will always filter everything out. Therefor the HANA Service translate it into `null = null` as the behavior is the same and does not …
> fix: improved `=` and `!=` with val `null` for HANA and Postgres

- db-service/lib/cqn2sql.js
- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- db-service/test/bookshop/db/booksWithExpr.cds
- db-service/test/cqn2sql/function.test.js
- db-service/test/cqn4sql/calculated-elements.test.js
- db-service/test/cqn4sql/functions.test.js
Not all possible defined combination where covered in regards to `func` objects. Mostly that `args` can be an `object` and that `func` and `xpr` can be combined for window functions. [docs](https://pages.github.tools.sap/cap/docs/cds/cxn#function-calls)
> feat: Add missing `func` cqn structures

- hana/package.json
Currently noticing the huge package is still coming in `@sap/cds-dk` with `@sap/hdi-deploy` version 5 because`@cap-js/hana` defines it as a non-optional peer dependency.
> deps: `@sap/hana-client` optional peer dependency

- db-service/lib/cqn4sql.js
- db-service/lib/infer/join-tree.js
- db-service/test/cqn4sql/assocs2joins.test.js
Consider this two path expressions:
`classrooms.classroom.ID, classrooms.classroom.name`
While the first path could be optimized to `classrooms.classroom_ID`, the second path is _not_ a key access and hence must be transformed to `classroom.name`, where `classroom` is the nested join node, refer to this example:
<details>
```js
const query = CQL`SELECT from Pupils {
ID
} group by classrooms.classroom.ID, classrooms.classroom.name`
const expected = CQL`SELECT from Pupils as Pupils
left join ClassroomsPupils as classrooms
on classrooms.pupil_ID = Pupils.ID
left join Classrooms as classroom
on classroom.ID = classrooms.classroom_ID
{
Pupils.ID
} group by classroom.ID, classroom.name`
```
</details>
As both paths navigate through the same join nodes, we do not (yet?) optimize the first path …
> fix: dont mistake non-key access with foreign key

- hana/lib/HANAService.js
When using `SELECT FROM DUMMY FOR JSON` the hex engine falls back to the legacy engines, but when replacing it with an equivalent statement it is possible to have the queries run in the hex engine.
Any suggestions for `FROM DUMMY` replacements are welcome.
> feat: Allow hex engine to be used

- db-service/test/cds-infer/nested-projections.test.js
The next cds-compiler version may be more restrictive on the "nested projections" syntax.  There should not be any space between `.` and `{`. Whether this restriction will actually make it into the next major is yet to decide.
> test(nested-projections): Adapt CDL syntax for upcoming major

- db-service/test/cqn4sql/expand.test.js
- db-service/test/cqn4sql/localized.test.js
- db-service/test/cqn4sql/where-exists.test.js
the `cds-compiler` will not produce `localized` views for transitive dependencies of `localized` artifacts.
That means an `Author` will not get a `localized.Authors` view just because there is an `author` association in the `localized` entity `Books`.
at some point those tests can be rewritten, but to test the deep replacement mechanism for `localized` artifacts it is fine for now to just explicitly set the `fewerLocalizedViews` option.
> test(`cds 8`): explicitly set `fewerLocalizedViews = false`

- hana/lib/HANAService.js
Adds `hana_simple_queries` feature flag. Which will make `@cap-js/hana` run all possible queries without `FOR JSON`. Which allows `hdb` and `@sap/hana-client` to returns different results again. 
Output converters are kept in place to reduce the likely hood of this happening. Current impacted test is `Bookshop - Order By › collations for aggregating queries with subselect`. Where the result of `sum(price) as pri` comes back as `"150"` for `@sap/hana-client` and `"1.5e+2"` for `hdb`. While expected is `150` in the `FOR JSON` result.
Additionally this PR removes the duplicate `"_json_"` output definition. Simplifying the SQL in all cases.
> feat: simple queries

- sqlite/test/deep/deepInputProcessing.test.js
- sqlite/test/lean-draft.test.js
- update does not return deep (as per odata spec)
- adjustment to fix in lean draft (with new adapter)
> chore: adjust tests for cds^8

- db-service/lib/cqn2sql.js
- postgres/lib/PostgresService.js
In the case of SQLite the simple queries are mostly compatible. When a `boolean` column is selected it is not considered a simple query as the result would be `"true" | "false"` which are both truthy.
In the case of Postgres a lot of number results are numbers where strings are expected and strings where numbers are expected.
> feat: Add simple queries feature flag

- hana/lib/HANAService.js
`this._done` is used from the default `tx` behavior. This can contain `committed` or `rolled back`. If `this._done` is not set it means the connection was never connected.
> fix: Improve error message for disconnected connections

- hana/lib/HANAService.js
- test/bookshop/package.json
- test/scenarios/bookshop/insert.test.js
hana-client:
`cds.Decimal` → `12345678901234567168`
`cds.Decimal(25,5)` → `12345678901234568244.75648`
hdb:
`cds.Decimal` → `1.2345678901234567168e+19`
`cds.Decimal(25,5)` → `12345678901234568244.75648`
It seems our INSERT erroneously manipulates the values on HANA.
Plain SQL insert ends in the expected result.
> fix: insertion of large decimals

- hana/cds-plugin.js
- hana/lib/HANAService.js
- hana/lib/drivers/base.js
- postgres/lib/PostgresService.js
- sqlite/lib/SQLiteService.js
- test/cds.js
- test/compliance/resources/db/basic/literals/basic.literals.timestamp.js
I've verified with this implementation that the creation of ISO function works during productive deployment.
However, the connection creation at runtime did not work because of the dynamic creation of the function at runtime. We should move that to the tests until there's a mechanism to hook into plain sql deployment.
@BobdenOs Could you check whether my change for test deployments is sufficient?
> fix: iso function creation

- hana/lib/HANAService.js
It's decided that the prerelase of cds 8 will not switch the default of `cds.env.features.string_decimals`.
In order to not lose precision on HANA with the prerelease, we have to remove the interpretation of the flag.
Maybe we should rename the flag in the future to be sqlite specific.
> chore: revert decimals are always strings on hana

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/expand.test.js
if we `select from <subquery>` we do not have a
`SELECT.from.ref` but the `<subquery>` has a `.target` because it has been inferred properly.
Use the name of the `.target` for building the correlated subquery, instead of dumping.
fix #708
> fix(`expand`): enable expanding from subquery

- hana/lib/HANAService.js
Currently when inserting `0` and `1` they are interpretated as `null` as they are not strictly matching `true` and `false`. With this change `0` and `1` are interpretated as their `truthy` and `falsy` values.
> fix: Allow numeric Booleans `0` and `1`

- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- db-service/test/cds-infer/negative.test.js
- db-service/test/cqn4sql/assocs2joins.test.js
in one case a ref `genre.parent.ID` was mistaken for a foreign key access because `ID` is fk of `parent`. But because `parent` is not fk of `genre`, it is actually not an fk access.
Hence, the reference actually needs to point to the correct join node.
> fix: rewrite assoc chains if intermediate assoc is not fk

- .github/workflows/hana.yml
- hana/tools/docker/hxe/Dockerfile
Update the HANA express image from `2.00.061.00.20220519.1` to `latest` (`2.00.072.00.20231123.1`)
> chore: Use new `latest` tag for hxe image

- db-service/lib/cql-functions.js
- hana/lib/cql-functions.js
- test/scenarios/bookshop/read.test.js
- test/scenarios/bookshop/search.test.js
This is the initial change to leverage the `SCORE` function from HANA to perform fuzzy searches. This is a greatly simplified implementation of the `SCORE` function as it comes with a large amount of configuration options.
> feat: Enable native HANA fuzzy search for `search` function queries

- hana/lib/HANAService.js
Currently getting a `TypeError` here when `credentials` is `undefined`.
Adapted version of our error message when the XSUAA credentials are not found.
> chore(hana): better error message with missing HANA credentials

- sqlite/lib/SQLiteService.js
docs: https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#new-databasepath-options
`options.fileMustExist`: if the database does not exist, an `Error` will be thrown instead of creating a new file. This option is ignored for in-memory, temporary, or readonly database connections (default: `false`).
With this any CRUD request does not create empty db files. It's obviously an error by developer but does not pollute the environment.
> fix: enforce db file to be existent before server start

- sqlite/lib/SQLiteService.js
This reverts commit 64a90186aaf44b3426df2e9adbf9a1b4cf2f92b7.
causes failures in stakeholder tests, reverting and double checking after major
> revert: "fix: enforce db file to be existent before server start (#742)"

- .github/workflows/release-please.yml
the other one is deprecated, as can be seen
in the annotations of [this workflow run](https://github.com/cap-js/cds-dbs/actions/runs/10001079480/attempts/1)
also got rid of unexpected inputs for github actions, we dont need them.
> ci: use new `release-please` action

- sqlite/test/lean-draft.test.js
The fix in https://github.com/cap-js/cds-dbs/pull/751 shows that we're still confused about when and how to access `cds.env` in combination with using `cds.test`. Long story short: 
- Ensure to call `cds.test()` or `cds.test.in()` before accessing `cds.env` anywhere
- see also: https://cap.cloud.sap/docs/node.js/cds-test#cds-test-env-check
Note that the `beforeAll` in https://github.com/cap-js/cds-dbs/pull/751 is actually _not_ required.
> chore: demystify cds.test and cds.env

- postgres/cds-plugin.js
this should not impact the dependencies of the actual node project, hence this is not a breaking change
> deps: build script generates cds8 dependency in deployer app

- release-please-config.json
It looks like `release-please` has hickups currently. By setting the `last-release-sha` we can force the tool to only search from our last release 0b8ecb614a3f1257896507d36edb989cab003bb7 → We need to change this after the next release ❗️
> chore: set last release in release-please config

- hana/tools/docker/hce/ready.sh
- hana/tools/docker/hce/start.sh
- hana/tools/docker/hxe/ready.sh
- hana/tools/docker/hxe/start.sh
- postgres/package.json
`docker-compose` (v1) has been replaced for a little while now with `docker compose` (v2), but for `Docker Desktop` there is an alias `docker-compose` which actually is (v2) which created a miss match between the GitHub Action and the local development setup as the container name changed from `hana_1` to `hana-1`. 
This PR aligns the two by switching to `docker compose` (v2) for the GitHub Actions as well. As the GitHub Action default runner seems to have removed the `docker-compose` (v1) command.
> chore: Migrate to docker compose v2

- db-service/lib/cql-functions.js
- test/scenarios/bookshop/search.test.js
Currently it is possible for `@cap-js/sqlite` and `@cap-js/postgres` to send invalid `$search` queries that make the request fail with `500` which should be succeeding with empty results.
> fix: prevent $search queries from throwing

- hana/lib/HANAService.js
when using `sql_simple_queries=1` and `hdb` the `NCLOB` columns are returned as `Buffers` not as `Strings`. With this change these columns include an output converters that informs `hdb` to handle them as `Strings`.
> fix: Enforce `LargeStrings` to be `Strings` for `sql_simple_queries=1`

- hana/lib/drivers/dynatrace.js
- hana/lib/drivers/hana-client.js
- hana/lib/drivers/hdb.js
todos:
it works (the yellow span):
> feat: wrap client if @dynatrace/oneagent-sdk is present

- db-service/lib/cqn4sql.js
- db-service/test/bookshop/db/schema.cds
- db-service/test/cqn4sql/table-alias.test.js
we need to drill recursively into the function arguments found in
on-conditions and prepend aliases of the outer query in case of scoped queries / expands
fixes #779
> fix: prepend aliases to refs within function args in on conditions

- release-please-config.json
Only merge after [#288](https://github.com/cap-js/cds-dbs/pull/761) got merged ‼️
> chore: remove latest sha from release-please config

- db-service/lib/deep-queries.js
- db-service/test/deep/deep.test.js
For `INSERT`s, `beforeData` is always `[]` and
```js
return beforeData.length ?? rootResult
```
would always return `0`.
> fix(deep-queries): properly return insert result

- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
[cap/dev] etc/perf.js
for (each of keys) if ...                  196 ms
for (each of keys) || ...                  188 ms
keys.filter.forEach (...)                  323 ms
> chore: use `for … of` + `if` instead of arrow func chaining

- db-service/lib/deep-queries.js
This reverts commit 3535a4e3ee4dd742931798d8e51381b1283f0e81.
the next hotfix should still be consumable in cds7 due to customer ticket.
> chore: revert "refactor: import of compareJSON (#814)"

- test/scenarios/bookshop/read.test.js
closes https://github.com/cap-js/cds-dbs/issues/812
issue was actually fixed with #837
> fix: usage of between operator

- postgres/package.json
This fix ensures that `postgres` build tasks do no longer get a warning marker and adds cds env code completion support.
> fix: add cds schema for postgres build plugin

- hana/lib/HANAService.js
- postgres/lib/PostgresService.js
- test/compliance/INSERT.test.js
- test/compliance/resources/db/basic/literals.cds
even though modeling is weird as the db default is anyway null, our implementation should go along with it.
closes https://github.com/cap-js/cds-dbs/issues/773
> fix: null as default value

- hana/lib/drivers/hana-client.js
The original optimization was put into place to prevent allocating to much memory when streaming large data from HANA. This change relies on the memory management capabilities of `nodejs` to detect when a `Buffer` is no longer being referenced. Making this code identical in all scenarios where the optimization was working as intended, but will allow scenarios where the `Buffer` is kept for an extended period of time to not be changed with following reads.
fixes: https://github.com/cap-js/cds-dbs/issues/788
> fix: allocate a new Buffer for each chunk of a Blob stream when using hana-client

- hana/lib/HANAService.js
- test/compliance/SELECT.test.js
- test/compliance/resources/db/basic/literals/basic.literals.number.js
closes https://github.com/cap-js/cds-dbs/issues/851
replaces https://github.com/cap-js/cds-dbs/pull/852
> fix: Adjust Decimal formatter to always render a whole number

- hana/lib/HANAService.js
- test/compliance/SELECT.test.js
Adds a test to reproduce an issue.
> fix: nested functions in comparisons

- hana/lib/HANAService.js
When using `@cap-js/hana` it is possible to send `SQL` statements like:
```sql
CALL PROC()
CALL SYS.PROC()
CALL "PROC"()
CALL "SYS"."PROC"()
```
With this change it is also possible to call procedures outside of the current schema or sys schema like:
```sql
CALL SCHEMA.PROC()
CALL "SCHEMA"."PROC"()
CALL "Schema"."Proc"()
```
The logic always was case sensitive for the procedure name therefor the same is applied to the schema name. This only applies to the metadata lookup for improved output parameter handling. As the native HANA drivers don't behave the same for procedure.
fixes: https://github.com/cap-js/cds-dbs/issues/859
> feat: Improve procedure metadata lookup logic

- hana/lib/HANAService.js
- hana/lib/drivers/hdb.js
fixes: https://github.com/cap-js/cds-dbs/blob/da629d98192cf1b196cceb172cb01f4a39acd887/test/compliance/resources/db/basic/literals/basic.literals.string.js#L41
The tests run with `hana-client` inside the pipelines. Tested locally works as expected.
> fix: enable `cesu8` by default for `hdb` driver and encode entries streams 

- db-service/lib/cqn2sql.js
- sqlite/lib/SQLiteService.js
For sql_simple_queries=2 elements of Boolean type are returned as strings due to the output converter. To correct this, we disable the boolean output converter for this feature flag.
> fix: boolean for sql_simple_queries 

- postgres/lib/PostgresService.js
- test/compliance/SELECT.test.js
- test/compliance/resources/db/data/basic.literals-string.csv
OData demands `NULLS FIRST` for `ASC` and `NULLS LAST` for `DESC`. SQLite, HANA behave like that, for Postgres the default is the opposite which is now changed.
> fix: enable nulls first

- db-service/lib/cqn2sql.js
- test/scenarios/bookshop/read.test.js
do not try to render an on-condition if none is provided
fix #897
fix #891
---
reproduced dump reported in the issues can be found [here](https://github.com/cap-js/cds-dbs/actions/runs/11891517718/job/33132429878?pr=899#step:7:264) fixed with 2e439b1dec9dac0d0a941f4717e2011e2fbde04c
> fix: cross joins w/o on-condition

- hana/package.json
This allows mac users with the `HANA_HOST` environment variable set to use the normal `npm t -w hana` command
> test: Skip start script for users with remote HANA configured

- db-service/lib/cql-functions.js
- hana/lib/cql-functions.js
- hana/test/hana-functions.test.js
- test/cds.js
According to https://cap.cloud.sap/docs/guides/databases#functions-mappings-for-runtime-queries
> For the SAP HANA functions, both usages are allowed: all-lowercase as given above, as well as all-uppercase.
> fix: SAP HANA functions should also be callable in upper case on SAP HANA

- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- db-service/test/cqn4sql/path-in-from.test.js
Rework #617
when the `infer` function was developed, it grew quite fast and some functions were tailor made for very specific use cases. While separation of concerns is a good practice w.r.t. maintainability, the wheel must not be re-invented for each minor deviation in behavior.
That being said, the two function `inferQueryElement` and `attachRefLinksToArg` are doing essentially the same. They both walk an `arg` which is - generally spoken - an expression. That might be a simple `ref`, `func`, `val` or a (nested) `xpr`.
- `inferQueryElement` was used for the `columns` of a query. Each column was resolved to a query element. All elements together formed the set of query elements. The other main part of the function is the attachment of the infamous `$refLinks` next to each `ref` array. …
> refactor(infer): consolidate two main functions

- db-service/lib/common/DatabaseService.js
otherwise, the transformed `data` is not considered.
introduced in #943
> chore: fix db.run('...',1,2,3,4)

- hana/package.json
- postgres/package.json
- sqlite/package.json
- test/find
Now that `cds-test` walks symbolic links it is no longer needed to have the `find` workaround. This allows now for simpler test file selection.
```
npm t -w sqlite SELECT.test.js           // runs /cds-dbs/sqlite/test/compliance/compliance/SELECT.test.js
npm t -w postgres bookshop/read.test.js  // runs /cds-dbs/postgres/test/compliance/scenarios/bookshop/read.test.js
npm t -w hana sflight                    // runs /cds-dbs/hana/test/compliance/scenarios/sflight/*.test.js
```
> test: Remove find workaround

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/not-persisted.test.js
as requested in `cap/issue#16975`
> fix: reject virtual elements in all expressions

- db-service/lib/cql-functions.js
- test/scenarios/bookshop/funcs.test.js
Compare the result of sqlite contains realization using `instr` to 0, to make it evaluate to a boolean. The same problem does not exist for HANA or Postgres.
> fix: contains not evaluting to bool

- hana/lib/HANAService.js
- test/scenarios/bookshop/read.test.js
fixes: https://github.com/cap-js/cds-dbs/issues/967
> fix: multi raw SQL queries

- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- db-service/test/cqn4sql/UPDATE.test.js
- db-service/test/cqn4sql/model/update.cds
the issue was that while calculating the `UPDATE.elements`, we accidentially assumed that the calculated element would lead to a join, hence we did our subselect matching. This logic is not necessary for non `SELECT` queries --> there we need joins if we do a `SELECT * from <entity with calculated element /w path expression>`
---
fix(`UPDATE`): no assocs in list which matches subquery results
> fix(`UPDATE`): only perform subselect matching if necessary

- hana/lib/HANAService.js
- postgres/lib/PostgresService.js
- sqlite/lib/SQLiteService.js
Add req.data to _not_unique function and set it to err.values.
> chore: add value property to db errors

- hana/lib/HANAService.js
- test/compliance/SELECT.test.js
- test/compliance/resources/db/complex/associations.cds
Currently, the HANA service is unable to `GROUP BY foobar.foobar`, raising an error like `invalid column name: foobar.foobar`, if the query includes an aggregation and `sql syntax error: incorrect syntax near "FROM"`, if it does not. The problem is caused by the overlapping column names and the HANA service not correctly injecting the column groupby requires into the parent select - if the parent includes a column with the same `column_name` as the 'grouped-by' column. 
This fix enables the required injection, by skipping the overlapping names check for columns that contain a select.
> fix: groupby path expression with overlapping identifier

- .release-please-manifest.json
- db-service/CHANGELOG.md
- db-service/package.json
- hana/CHANGELOG.md
- hana/package.json
- postgres/CHANGELOG.md
- postgres/package.json
- sqlite/CHANGELOG.md
- sqlite/package.json
This reverts commit 0b1b533fffe26f64b7ef590acdce9e9bb7b6031f.
required to retrigger release
> chore: revert "chore: release main (#961)"

- db-service/lib/infer/index.js
- db-service/test/cds-infer/elements.test.js
- db-service/test/cqn4sql/table-alias.test.js
referencing the query elements (i.e. other columns) of the query must also be possible if the $self reference is nested in an expression.
> fix: nested $self reference to other column

- hana/lib/HANAService.js
Some queries based upon sub selects would be considered `_unresolved`, but `infer` is able to make them `resolved`.
> fix: infer when unresolved

- hana/lib/drivers/base.js
- hana/lib/drivers/hana-client.js
- hana/lib/drivers/hdb.js
- hana/tools/docker/hce/hana.yml
- hana/tools/docker/hce/jaeger.yaml
- hana/tools/docker/hce/otel.sh
- hana/tools/docker/hce/prometheus.yml
- hana/tools/docker/hce/ready.sh
This PR adds a `jaeger` and `prometheus` docker image to the `hce` docker setup. This allow the HANA Cloud instance to share its trace information with the `jaeger` Open Telemetry trace APIs. The value that the `prometheus` image provides is the ability to use the `monitoring` view of `jaeger`. Which aggregates the trace information to highlight possible performance pain points.
By leveraging `@cap-js/telemetry`, `SAP Passport` and `HANA` traces. It is possible to get a full stack performance overview while in a local development environment. Which is usually only possible in productive landscapes by using `dynatrace`. By having the detailed trace information locally it enables experimental analysis which is not possible in productive landscapes. Additionally removing the hyper scaler …
> test: add jaeger docker image with HANA trace information

- .github/workflows/test.yml
- postgres/package.json
- postgres/test/cds-build.test.js
- postgres/test/tiny-sample/db/data/my.bookshop-Books.csv
- postgres/test/tiny-sample/db/schema.cds
- postgres/test/tiny-sample/package.json
- postgres/test/tiny-sample/srv/cat-service.cds
as reported in the issue, with default `cds build --production` no postgres build artifacts have been generated.
this was due to a misconfiguration in our `postgres/package.json`
---
```shell
cds init reproduce --add tiny-sample
cd reproduce
cds add postgres
```
you can now observe the malformed `cds env`
```shell
❯ cds env requires.db --profile production
{
impl: '@cap-js/postgres',
credentials: { url: 'db.sqlite' },
kind: 'sqlite',
dialect: 'postgres',
vcap: { label: 'postgresql-db' },
schema_evolution: 'auto'
}
```
and the broken build (missing postgres build task):
```
❯ cds build --production
building project [/Users/patricebender/SAPDevelop/dev/cds-dbs/postgres/test/tiny-sample], clean [true]
cds-dk [8.7.1], cds [8.8.0], compiler [5.7.5], home …
```
> fix: postgres build plugin w `--production`

- db-service/lib/infer/index.js
This change not only removes the potential for catastrophic backtracking, but it is also more direct and generally more efficient, resolves:
https://github.com/cap-js/cds-dbs/security/code-scanning/4 & https://github.com/cap-js/cds-dbs/security/code-scanning/3
> fix: replace polynomial regex with simple string op

- .github/workflows/release-please.yml
- .github/workflows/release.yml
as suggested by:
https://github.com/cap-js/cds-dbs/security/code-scanning/1 https://github.com/cap-js/cds-dbs/security/code-scanning/2
> ci: pin versions for 3rd party github actions

- sqlite/test/general/managed.test.js
This assertion frequently fails locally on my M2 machine, presumably because it only works on slow machines?
If so what will happen when I get an M4? ;)
> test: 2fast4us?

- test/scenarios/bookshop/read.test.js
To prepare for consolidation of cds.infer
> refactor: SELECT.from() was never meant to support cross joins 

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/expand.test.js
enable the following:
```js
cds.ql`SELECT name, books[order by price] { * } FROM Authors`
```
it is still possible to have query modifiers defined as sibling property to `expand`:
```js
{
ref: ['author'],
expand: [
{
ref: ['name'],
},
],
limit: {
offset: {
val: 1,
},
rows: {
val: 1,
},
},
orderBy: [
{
ref: ['name'],
sort: 'asc',
},
],
}
```
--> If both are set, the modifiers in the `ref` of the expanded association have precedence
> feat: query modifiers on expand `ref` are propagated to subquery

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/expand.test.js
this resolves an `Uncaught Object.defineProperty called on non-object` dump
this is a workaround for an issue reported in cap/issues#17907
--> we need to put all this logic in the OData protocol adapter, this coding should not be necessary for the DB. This initiative has already started in #990
> fix: expand + groupby may return null, dont attach `.element`

- db-service/lib/cqn2sql.js
logged in the same format here: https://github.com/cap-js/cds-dbs/blob/cf2e0a215e89f9055e28d9f0984adf292e220aee/db-service/lib/SQLService.js#L294C22-L294C26
> fix: align debug log format of stmt values

- .github/workflows/test.yml
- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/where-exists.test.js
if `from.ref.at(-1).where` contains any logical operator such as
`and` or `or`, we must wrap the filter condition in an `xpr` so that
it is quoted in `toSQL` to avoid operator precedence issues.
fix cap/issue#18155
> fix(scoped queries): wrap filter in `xpr` if needed

- .release-please-manifest.json
- db-service/CHANGELOG.md
- db-service/package.json
This reverts commit 810781dfd93cd0d76a0ccb0055b020b41fe352b0.
due to messed up cds-dk dependencies, the release did not make it to npm
> chore: Revert "chore: release main (#1106)"

- db-service/lib/infer/index.js
- db-service/test/cqn4sql/where-exists.test.js
in a column expression, an `exists` predicate was not always properly detected, the absence of this information lead to a an error because of subsequent "dangling" filter conditions, which are usually not allowed with the exception of being used in combination with the `exists` predicate.
> fix: exists within expression is properly detected

- sqlite/test/general/managed.test.js
prepares for `cds.runtime.put_as_replace` (regardless of what the default will be)
> chore: put defaults not provided only with `cds.runtime.put_as_replace = true`

- db-service/lib/cqn2sql.js
- test/compliance/resources/db/basic/common.cds
- test/compliance/resources/db/basic/common/basic.common.default.js
- HANA doesn't allow functions as default values. 
- `current_utctimestamp()` looks like an exception
- asked by stakeholder
> fix: current_utctimestamp as default

- db-service/lib/cqn4sql.js
- db-service/lib/infer/index.js
- db-service/lib/utils.js
- db-service/test/cds-infer/api.test.js
see cap/issues#18378
---
**TL;DR** customer manipulated the `order by` of an already-fired query and ran the query again. The `isJoinRelevant` flag indicated the _old_ state of the column which has been changed to a foreign key access which obviously does not need a join. As a result, the `order by` token had messed up meta information attached which led to an undefined state.
the issue is described as a test in this pr:
```js
it('infer inferred query multiple times, even after manipulation', () => {
const flatModel = cds.compile.for.nodejs(model)
// the order by path is join relevant
let query = cds.ql`SELECT from bookshop.Genres { ID, parent_ID } order by parent.name`
let inferred = _inferred(query, flatModel)
/*
now the order by path is not join relevant anymore
if the orderBy's …
```
> fix: resilience for query re-use scenarios

- db-service/test/deep/package.json
- test/bookshop/package.json
- test/sflight/package.json
As discussed in the stand up: doesn't really matter for npm install but is better that way
> chore: Consolidating packages dependencies in nested tests

- .github/workflows/reject-pr.yml
until cds9 is released, we need to make sure that PR authors do not break the code integrity _manually_.
This workflow helps with this and points to our matrix tests, for increased accessibility.
> ci: add workflow which fails fast and points to local testing

- db-service/lib/search.js
- db-service/test/bookshop/db/search.cds
- db-service/test/cqn4sql/search.test.js
the `@cds.search` annotation is propagated as-is.
If a path expression was used in the `@cds.search` annotation of a base entity, but the association for the path is _not_ projected in a view on top of the entity, we must not try to resolve the path expression in the view.
reported in cap/issue#18465
> fix(`search`): do not search on non-projected elements

- test/compliance/INSERT.test.js
- test/compliance/resources/db/basic/common.cds
This test already ensures that `default $now` is using the session context instead of current_timestamp for generating the default value.
It has to be done in the SQL statement since the compiler generates current_timestamp in the default clause since the db do not allow usage of session context for default clauses.
> test: ensure default $now always points to tx timestamp

- hana/lib/HANAService.js
- test/compliance/SELECT.test.js
- test/compliance/resources/db/basic/projection.cds
compiler will change the $now references in views with SESSION_CONTEXT('NOW'). so far it's CURRENT_TIMESTAMP
> feat: set NOW as session var in addition to $now

- db-service/lib/common/generic-pool.js
- hana/lib/HANAService.js
As just discussed with @johannes-vogel and @chgeo :
Subsequently: 
Reason for the changed flag: With the former opt in flag set globally, lots of tests and samples which intentionally didn't use a database at all were broken. ( The former flag is still supported w/ this PR though )
> fix: Better opt in flag for builtin generic pool

- db-service/lib/cqn2sql.js
Where clauses like `where exists SELECT ...` are not supported in `START WHERE`, therefore such SELECTs are wrapped in `where ID in ...`.
> feat(recurse): object-page hierarchies

- hana/lib/HANAService.js
Currently the HDI Container group isolation layer doesn't provide the isolation required for the parallel test execution. While the container group doesn't contain the container the container name clashes with those of the other container groups. Creating undefined behaviors additionally the user groups don't provide any isolation resulting in the creating side effects of creating users with the same name.
> test: Improve test isolation logic for HANA containers

- postgres/lib/PostgresService.js
Under certain conditions, the chunks written by the `ParameterStream` class were transmitted in the wrong order:
In this example, there was a correct copydata header with length 0x158 written to the stream, but the header of another chunk with length 0x11 was transmitted first.
This leads to errors like these because copydata message headers/announced lengths do not match the actual message length:
`Error in ParameterStream: error: unexpected message type 0x6B during COPY from stdin`
I could only observe the issue with TLS enabled (local/BTP) Postgres, so it looks like TLS sockets are a bit more sensitive to timing. It happens predictably for me there, though. Also it never happened with the patches included in this PR, so there is hope that it actually resolves the issue.
It could be …
> fix: ensure ordering of `ParameterStream` chunks

- db-service/lib/cqn4sql.js
- db-service/test/cqn4sql/column.element.test.js
→ in the changed `if` branch, we (re) set the leaf link again to the last association. However, the path in the column already drilled down to the respective element. We just need to propagate the already calculated element and attach it to the flat column.
Before this change, in this particular case the association (`parent` in the test) was erroneously set as `element` link for the column, which led to a faulty `cqn2sql` rendering down the line.
> fix: set proper element link for path into fk

- sqlite/test/search.test.js
--> after #1341 has been merged, we can enable this test with the proper expectation
> test(`@cds.search`): enable test with `to-many` deduplication

- db-service/lib/search.js
- db-service/test/bookshop/db/search.cds
- db-service/test/cqn4sql/search.test.js
- sqlite/test/search.test.js
With this change:
- associations/compositions in @cds.search are additive
- all other elements override the default search elements
- i.e. also paths with length > 1 like `books.title` override the default search elements
- virtual elements are _always_ ignored and hence do not override defaults search elements
closes #1347
> fix: associations in `@cds.search` are additive
